import Head from "next/head";
import Image from "next/image";
import Card from "../components/Card";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/* the Hero section */}

			<section className="container-fluid hero bg-gray-500">
				<div className="flex flex-col items-center">
					<div>
						<img src="/img/logo_img.png" alt="" />
					</div>
				</div>
			</section>

			<div className="flex justify-center ">
				<div className="container md:w-[750px] w-full shadow-sm p-5 box bg-white rounded border">
					<h2 className="text-2xl">All Competitions</h2>
					<div className="flex flex-wrap">
						<Card />
						<Card />
						<Card />
					</div>
				</div>
			</div>

			{/* The footer section */}
			<footer>
				<div className="row my-8">
					<div className="flex-col text-center">
						<p>
							<span className="text-gray-700">Built by </span>
							<a href="#" className="border-b-2">
								Aneal EmekaH
							</a>
						</p>
						<p>
							Credits <a href="#">Football Data API</a>
						</p>
					</div>
				</div>
			</footer>
		</div>
	);
}
